export enum AgentHealth {
  NOT_INSTALLED = 'NOT_INSTALLED',
  INSTALLED = 'INSTALLED',
  LAUNCHABLE = 'LAUNCHABLE',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  READY = 'READY',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN'
}
